### ISSUE TITLE
BBOBB does not works with pair number of machines

### ISSUE THREAD

**Issue by juliette39** [simatic/FBAE#32]
In BBOBBAlgoLayer.cpp line 205
replace
`nbStepsInWave = static_cast<int>(n % 2 == 0 ? log2(n) : ceil(log2(n)));`
by
`nbStepsInWave = static_cast<int>(static_cast<int>(std::floor(log2(n))) == log2(n) ? log2(n) : ceil(log2(n)));`

**Comment by simatic** [comment]
Issue solved with Merge request https://github.com/simatic/FBAE/pull/33

Instead of using math functions to compute `nbStepsInWave`, we increment it at each step of the loop `for (int power_of_2 = 1; power_of_2 < sites.size(); power_of_2 *= 2) {}`
